default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bitflash_development

test:
  <<: *default
  database: bitflash_test

production:
  <<: *default
  database: bitflash_production
  username: bitflash
  password: <%= ENV['BITFLASH_DATABASE_PASSWORD'] %>
